### ISSUE TITLE
Code Citation

### ISSUE THREAD

**Issue by augustfly** [kasperschmidt/GLASSinspectionGUIs#1]
Hi,

We have your coauthored paper in post-acceptance with this software described and used in an Appendix. Per the [AAS Journals software policy](http://journals.aas.org/policy/software.html), we request that you [mint a DOI](https://guides.github.com/activities/citable-code/) to the current release of this software. That DOI will be entered into final manuscript's reference list. 

Please carefully curate the metadata related to this DOI release. We have some [recommendations](https://github.com/AASJournals/Tutorials/blob/master/Repositories/UsingRepositories.md#curating-your-repository) in the journal's [repository tutorial](https://github.com/AASJournals/Tutorials/tree/master/Repositories). 

If you have any questions then we can talk about them here or on our [ticket system](mailto:data-editors@aas.org)

thanks.

**Comment by kasperschmidt** [comment]
The mentioned publication is Vulcani et al. (2016), The Astrophysical Journal, 833:178. A DOI was generated for the third release of GiG (https://github.com/kasperschmidt/GLASSinspectionGUIs/releases/tag/v3.0) at https://zenodo.org/record/161686
